#!/usr/bin/env node
/**
 * AgencyFlow Setup Script
 * Run: node scripts/setup.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(r => rl.question(q, r));

const colors = {
  reset: '\x1b[0m', bright: '\x1b[1m', green: '\x1b[32m',
  cyan: '\x1b[36m', yellow: '\x1b[33m', red: '\x1b[31m', purple: '\x1b[35m'
};

const c = (color, text) => `${colors[color]}${text}${colors.reset}`;

async function main() {
  console.clear();
  console.log(c('purple', c('bright', '╔══════════════════════════════════════════╗')));
  console.log(c('purple', c('bright', '║      AgencyFlow — Setup Wizard           ║')));
  console.log(c('purple', c('bright', '║      Automation for Digital Agencies      ║')));
  console.log(c('purple', c('bright', '╚══════════════════════════════════════════╝')));
  console.log('');

  // Create directories
  ['data'].forEach(dir => {
    const p = path.join(__dirname, '..', dir);
    if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
  });

  console.log(c('cyan', '📋 Step 1: Agency Details'));
  const agencyName = await ask('  Agency name: ');
  const founderName = await ask('  Your name: ');
  const agencyEmail = await ask('  Your email: ');
  const agencyPhone = await ask('  Your phone: ');

  console.log('');
  console.log(c('cyan', '🔑 Step 2: API Keys'));
  console.log(c('yellow', '  (Press Enter to skip — you can set these later in .env)'));
  const aiProvider = (await ask('  AI provider [openrouter/groq/anthropic] (default: openrouter): ')) || 'openrouter';
  const openRouterKey = await ask('  OpenRouter API key (free models): ');
  const groqKey = await ask('  Groq API key (free tier): ');
  const anthropicKey = await ask('  Anthropic API key (optional): ');
  const smtpUser = await ask('  Gmail address (SMTP): ');
  const smtpPass = await ask('  Gmail App Password: ');
  const messagingProvider = (await ask('  Messaging provider [telegram/twilio] (default: telegram): ')) || 'telegram';
  const telegramBotToken = await ask('  Telegram Bot Token (free): ');
  const telegramChatId = await ask('  Telegram Chat ID: ');
  const twilioSid = await ask('  Twilio Account SID (optional): ');
  const twilioToken = await ask('  Twilio Auth Token (optional): ');
  const notifyWA = await ask('  Your WhatsApp number for Twilio notifications (optional): ');
  const slackWebhook = await ask('  Slack Webhook URL (optional): ');

  console.log('');
  console.log(c('cyan', '📊 Step 3: Data Storage'));
  const excelFilePath = (await ask('  Excel file path (default: ./data/leads.xlsx): ')) || './data/leads.xlsx';
  const clientOutreachFilePath = (await ask('  Client outreach Excel file path (optional): ')) || './data/FreelanceClientOutreach.xlsx';
  const incomeFilePath = (await ask('  Income tracker Excel file path (optional): ')) || './data/FreelanceIncomeTracker.xlsx';
  const expenseFilePath = (await ask('  Expense tracker Excel file path (optional): ')) || './data/FreelanceExpenseTracker.xlsx';
  const sheetId = await ask('  Google Spreadsheet ID (optional): ');

  // Write .env
  const env = `# AgencyFlow Configuration
# Generated by setup wizard

PORT=3000

AGENCY_NAME=${agencyName}
FOUNDER_NAME=${founderName}
AGENCY_EMAIL=${agencyEmail}
AGENCY_PHONE=${agencyPhone}

AI_PROVIDER=${aiProvider}
OPENROUTER_API_KEY=${openRouterKey || ''}
OPENROUTER_MODEL=meta-llama/llama-3.1-8b-instruct:free
GROQ_API_KEY=${groqKey || ''}
GROQ_MODEL=llama-3.1-8b-instant
ANTHROPIC_API_KEY=${anthropicKey || ''}
ANTHROPIC_MODEL=claude-sonnet-4-20250514

SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=${smtpUser || ''}
SMTP_PASS=${smtpPass || ''}

MESSAGING_PROVIDER=${messagingProvider}
TELEGRAM_BOT_TOKEN=${telegramBotToken || ''}
TELEGRAM_CHAT_ID=${telegramChatId || ''}

TWILIO_ACCOUNT_SID=${twilioSid || ''}
TWILIO_AUTH_TOKEN=${twilioToken || ''}
TWILIO_WHATSAPP_FROM=+14155238886
NOTIFY_WHATSAPP=${notifyWA || ''}

EXCEL_FILE_PATH=${excelFilePath}
CLIENT_OUTREACH_FILE_PATH=${clientOutreachFilePath}
INCOME_FILE_PATH=${incomeFilePath}
EXPENSE_FILE_PATH=${expenseFilePath}
GOOGLE_CREDENTIALS_PATH=./data/google-credentials.json
DEFAULT_SHEET_ID=${sheetId || ''}

SLACK_WEBHOOK_URL=${slackWebhook || ''}
`;

  fs.writeFileSync(path.join(__dirname, '..', '.env'), env);

  // Write settings.json
  const settings = { agencyName, founderName, email: agencyEmail, phone: agencyPhone, services: 'Web Design, Logo Design, Social Media Management, Content Writing, SEO, Digital Marketing' };
  fs.writeFileSync(path.join(__dirname, '..', 'data', 'settings.json'), JSON.stringify(settings, null, 2));

  rl.close();

  console.log('');
  console.log(c('green', '✅ Setup complete!'));
  console.log('');
  console.log(c('bright', 'Next steps:'));
  console.log(`  1. ${c('cyan', 'npm install')} — install dependencies`);
  console.log(`  2. ${c('cyan', 'npm start')} — start the server`);
  console.log(`  3. Open ${c('cyan', 'http://localhost:3000')} in your browser`);
  console.log('');
  console.log(c('yellow', '📡 Webhook URLs (point these to your integrations):'));
  console.log(`  Contact Form: ${c('green', 'POST http://localhost:3000/webhook/contact_form')}`);
  console.log(`  WhatsApp:     ${c('green', 'POST http://localhost:3000/webhook/whatsapp')}`);
  console.log('');

  if (!openRouterKey && !groqKey && !anthropicKey) {
    console.log(c('yellow', '⚠  No AI API key configured. AI nodes will not work.'));
    console.log('   Recommended free option: https://openrouter.ai');
    console.log('   Then update AI_PROVIDER and API key in .env');
    console.log('');
  }

  console.log(c('purple', '🚀 Ready to automate your agency!'));
}

main().catch(e => { console.error(e); process.exit(1); });
